### ISSUE TITLE
Change interactive selection of ssh keys

### ISSUE THREAD

**Issue by katia-e** [Jumpscale/core9#193]
#### Installation information

- jumpscale version: js9,  
- branch: `development`
- operating system: ubuntu 16:04

#### Detailed description
issue appeared when running `zrobot` server that interactively requested to choose an ssh key.
![screenshot from 2018-02-07 12-03-18](https://user-images.githubusercontent.com/32639869/35914073-318d9932-0c02-11e8-8133-9764ac7d6537.png)

https://github.com/Jumpscale/0-robot/issues/67

#### Steps to reproduce
- kill ssh-agent; remove existing ssh key js9 config
- run zrobot
 - run blueprint
``` yaml
services:
    - github.com/openvcloud/0-templates/sshkey/0.0.1__key:
        path: '/root/.ssh/id_rsa'
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__be-g8-3:
        address: 'be-g8-3.demo.greenitglobe.com'
        login: 'ekaterina_evdokimova_1@itsyouonline'
        token: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJxbkJqZXVyNmFXdTJaY3Vzd1o5c3pvcDc1dDBNIiwiZXhwIjoxNTE4MDg3NDYzLCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJzY29wZSI6WyJ1c2VyOmFkbWluIl0sInVzZXJuYW1lIjoiZWthdGVyaW5hX2V2ZG9raW1vdmFfMSJ9.ImUWU16FbrFWwSIcgh_pWmMAcyd-rQTrD2aejBDKcCcsC4rap8mDWVnAcq3zzI5JzW2A238Kh5GKM-WrDOBqFsoAwzwDjcldUvaKs6f-deoV7NALf1yAi9s1yNUWO52O'
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__ekaterina_evdokimova_1:
        provider: itsyouonline
        email: ekaterina@gig.tech
    - github.com/openvcloud/0-templates/account/0.0.1__katia01:

actions:
    - template: github.com/openvcloud/0-templates/account/0.0.1
      actions: ['install']
```
